const BUTTONS = {
  grave: {
    value: '`',
    shiftValue: '~',
    valueRu: 'ё',
    shiftValueRu: 'Ё',
    isFunc: false,
  },
  one: {
    value: '1',
    shiftValue: '!',
    valueRu: '1',
    shiftValueRu: '!',
    isFunc: false,
  },
  two: {
    value: '2',
    shiftValue: '@',
    valueRu: '2',
    shiftValueRu: '"',
    isFunc: false,
  },
  three: {
    value: '3',
    shiftValue: '#',
    valueRu: '3',
    shiftValueRu: '№',
    isFunc: false,
  },
  four: {
    value: '4',
    shiftValue: '$',
    valueRu: '4',
    shiftValueRu: ';',
    isFunc: false,
  },
  five: {
    value: '5',
    shiftValue: '%',
    valueRu: '5',
    shiftValueRu: '%',
    isFunc: false,
  },
  six: {
    value: '6',
    shiftValue: '^',
    valueRu: '6',
    shiftValueRu: ':',
    isFunc: false,
  },
  seven: {
    value: '7',
    shiftValue: '&',
    valueRu: '7',
    shiftValueRu: '?',
    isFunc: false,
  },
  eight: {
    value: '8',
    shiftValue: '*',
    valueRu: '8',
    shiftValueRu: '*',
    isFunc: false,
  },
  nine: {
    value: '9',
    shiftValue: '(',
    valueRu: '9',
    shiftValueRu: '(',
    isFunc: false,
  },
  zero: {
    value: '0',
    shiftValue: ')',
    valueRu: '0',
    shiftValueRu: ')',
    isFunc: false,
  },
  dash: {
    value: '-',
    shiftValue: '_',
    valueRu: '-',
    shiftValueRu: '_',
    isFunc: false,
  },
  equal: {
    value: '=',
    shiftValue: '+',
    valueRu: '=',
    shiftValueRu: '+',
    isFunc: false,
  },
  bSpace: {
    name: 'Backspace',
    value: '',
    shiftValue: '',
    valueRu: '',
    shiftValueRu: '',
    isFunc: true,
  },
  tab: {
    name: 'Tab',
    value: '    ',
    shiftValue: '    ',
    valueRu: '    ',
    shiftValueRu: '    ',
    isFunc: true,
  },
  q: {
    value: 'q',
    shiftValue: 'Q',
    valueRu: 'й',
    shiftValueRu: 'Й',
    isFunc: false,
  },
  w: {
    value: 'w',
    shiftValue: 'W',
    valueRu: 'ц',
    shiftValueRu: 'Ц',
    isFunc: false,
  },
  e: {
    value: 'e',
    shiftValue: 'E',
    valueRu: 'у',
    shiftValueRu: 'У',
    isFunc: false,
  },
  r: {
    value: 'r',
    shiftValue: 'R',
    valueRu: 'к',
    shiftValueRu: 'К',
    isFunc: false,
  },
  t: {
    value: 't',
    shiftValue: 'T',
    valueRu: 'е',
    shiftValueRu: 'Е',
    isFunc: false,
  },
  y: {
    value: 'y',
    shiftValue: 'Y',
    valueRu: 'н',
    shiftValueRu: 'Н',
    isFunc: false,
  },
  u: {
    value: 'u',
    shiftValue: 'U',
    valueRu: 'г',
    shiftValueRu: 'Г',
    isFunc: false,
  },
  i: {
    value: 'i',
    shiftValue: 'I',
    valueRu: 'ш',
    shiftValueRu: 'Ш',
    isFunc: false,
  },
  o: {
    value: 'o',
    shiftValue: 'O',
    valueRu: 'щ',
    shiftValueRu: 'Щ',
    isFunc: false,
  },
  p: {
    value: 'p',
    shiftValue: 'P',
    valueRu: 'з',
    shiftValueRu: 'З',
    isFunc: false,
  },
  lBracket: {
    value: '[',
    shiftValue: '{',
    valueRu: 'х',
    shiftValueRu: 'Х',
    isFunc: false,
  },
  rBracket: {
    value: ']',
    shiftValue: '}',
    valueRu: 'ъ',
    shiftValueRu: 'Ъ',
    isFunc: false,
  },
  bSlash: {
    value: '\\',
    shiftValue: '|',
    valueRu: '\\',
    shiftValueRu: '/',
    isFunc: false,
  },
  del: {
    name: 'Del',
    value: '',
    shiftValue: '',
    valueRu: '',
    shiftValueRu: '',
    isFunc: true,
  },
  caps: {
    name: 'CapsLock',
    value: '',
    shiftValue: '',
    valueRu: '',
    shiftValueRu: '',
    isFunc: true,
  },
  a: {
    value: 'a',
    shiftValue: 'A',
    valueRu: 'ф',
    shiftValueRu: 'Ф',
    isFunc: false,
  },
  s: {
    value: 's',
    shiftValue: 'S',
    valueRu: 'ы',
    shiftValueRu: 'Ы',
    isFunc: false,
  },
  d: {
    value: 'd',
    shiftValue: 'D',
    valueRu: 'в',
    shiftValueRu: 'В',
    isFunc: false,
  },
  f: {
    value: 'f',
    shiftValue: 'F',
    valueRu: 'а',
    shiftValueRu: 'А',
    isFunc: false,
  },
  g: {
    value: 'g',
    shiftValue: 'G',
    valueRu: 'п',
    shiftValueRu: 'П',
    isFunc: false,
  },
  h: {
    value: 'h',
    shiftValue: 'H',
    valueRu: 'р',
    shiftValueRu: 'Р',
    isFunc: false,
  },
  j: {
    value: 'j',
    shiftValue: 'J',
    valueRu: 'о',
    shiftValueRu: 'О',
    isFunc: false,
  },
  k: {
    value: 'k',
    shiftValue: 'K',
    valueRu: 'л',
    shiftValueRu: 'Л',
    isFunc: false,
  },
  l: {
    value: 'l',
    shiftValue: 'L',
    valueRu: 'д',
    shiftValueRu: 'Д',
    isFunc: false,
  },
  semicolon: {
    value: ';',
    shiftValue: ':',
    valueRu: 'ж',
    shiftValueRu: 'Ж',
    isFunc: false,
  },
  qMark: {
    value: '\'',
    shiftValue: '"',
    valueRu: 'э',
    shiftValueRu: 'Э',
    isFunc: false,
  },
  enter: {
    name: 'Enter',
    value: '\n',
    shiftValue: '\n',
    valueRu: '\n',
    shiftValueRu: '\n',
    isFunc: true,
  },
  lShift: {
    name: 'Shift',
    value: '',
    shiftValue: '',
    valueRu: '',
    shiftValueRu: '',
    isFunc: true,
  },
  z: {
    value: 'z',
    shiftValue: 'Z',
    valueRu: 'я',
    shiftValueRu: 'Я',
    isFunc: false,
  },
  x: {
    value: 'x',
    shiftValue: 'X',
    valueRu: 'ч',
    shiftValueRu: 'Ч',
    isFunc: false,
  },
  c: {
    value: 'c',
    shiftValue: 'C',
    valueRu: 'с',
    shiftValueRu: 'С',
    isFunc: false,
  },
  v: {
    value: 'v',
    shiftValue: 'V',
    valueRu: 'м',
    shiftValueRu: 'М',
    isFunc: false,
  },
  b: {
    value: 'b',
    shiftValue: 'B',
    valueRu: 'и',
    shiftValueRu: 'И',
    isFunc: false,
  },
  n: {
    value: 'n',
    shiftValue: 'N',
    valueRu: 'т',
    shiftValueRu: 'Т',
    isFunc: false,
  },
  m: {
    value: 'm',
    shiftValue: 'M',
    valueRu: 'ь',
    shiftValueRu: 'Ь',
    isFunc: false,
  },
  comma: {
    value: ',',
    shiftValue: '<',
    valueRu: 'б',
    shiftValueRu: 'Б',
    isFunc: false,
  },
  dot: {
    value: '.',
    shiftValue: '>',
    valueRu: 'ю',
    shiftValueRu: 'Ю',
    isFunc: false,
  },
  slash: {
    value: '/',
    shiftValue: '?',
    valueRu: '.',
    shiftValueRu: ',',
    isFunc: false,
  },
  tArrow: {
    value: '▲',
    shiftValue: '▲',
    valueRu: '▲',
    shiftValueRu: '▲',
    isFunc: false,
  },
  rShift: {
    name: 'Shift',
    value: '',
    shiftValue: '',
    valueRu: '',
    shiftValueRu: '',
    isFunc: true,
  },
  lCtrl: {
    name: 'Ctrl',
    value: '',
    shiftValue: '',
    valueRu: '',
    shiftValueRu: '',
    isFunc: true,
  },
  win: {
    name: 'Win',
    value: '',
    shiftValue: '',
    valueRu: '',
    shiftValueRu: '',
    isFunc: true,
  },
  lAlt: {
    name: 'Alt',
    value: '',
    shiftValue: '',
    valueRu: '',
    shiftValueRu: '',
    isFunc: true,
  },
  space: {
    value: ' ',
    shiftValue: ' ',
    valueRu: ' ',
    shiftValueRu: ' ',
    isFunc: false,
  },
  rAlt: {
    name: 'Alt',
    value: '',
    shiftValue: '',
    valueRu: '',
    shiftValueRu: '',
    isFunc: true,
  },
  lArrow: {
    value: '◄',
    shiftValue: '◄',
    valueRu: '◄',
    shiftValueRu: '◄',
    isFunc: false,
  },
  dArrow: {
    value: '▼',
    shiftValue: '▼',
    valueRu: '▼',
    shiftValueRu: '▼',
    isFunc: false,
  },
  rArrow: {
    value: '►',
    shiftValue: '►',
    valueRu: '►',
    shiftValueRu: '►',
    isFunc: false,
  },
  rCtrl: {
    name: 'Ctrl',
    value: '',
    shiftValue: '',
    valueRu: '',
    shiftValueRu: '',
    isFunc: true,
  },
};

export default BUTTONS;
